// Generated by the Kof compiler — KofJS runtime. Do not edit.
// Reachability-based content: only what the program reaches.
// kof:seeds kofListAdd,kofListGet,kofListNew,kofPrintln,kofTimeInterval,kofUiAudioNew,kofUiAudioPlay,kofUiAudioSetSrc,kofUiButtonNewAction,kofUiCanvasBeginPath,kofUiCanvasClosePath,kofUiCanvasFill,kofUiCanvasLineTo,kofUiCanvasMoveTo,kofUiCanvasNew,kofUiCanvasSetFill,kofUiColumnNew,kofUiLabelNew,kofUiLinkNew,kofUiRowNew,kofUiWidgetOn,kofUiWindowBind,kofUiWindowNew,kofUiWindowSetTitle,kofUiWindowShow
// kof:units 64/701

// KofJS core runtime — platform-neutral helpers.
// Generated by the Kof compiler (KofJS backend).
// This module is not a VM: it only provides operations that
// JavaScript does not represent directly.

// #104: kof_platform só existe no host GraalJS; shim fora dele
// (Node/browser) troca ReferenceError por erro claro (#104).
if (!globalThis.kof_platform) {
    globalThis.kof_platform = new Proxy({
        print(x) { console.log(String(x)); }
    }, {
        get(t, prop) {
            if (prop in t) return t[prop];
            return function () {
                throw new Error("kof_platform." + String(prop)
                        + ": not available outside the Kof JS host");
            };
        }
    });
}

if (typeof document === "undefined") {
    function kofMakeEl(tag) {
        const attrs = {};
        const el = {
            tagName: String(tag).toUpperCase(),
            id: null,
            className: "",
            textContent: "",
            value: "",
            checked: false,
            readOnly: false,
            disabled: false,
            selectedIndex: -1,
            href: "",
            target: "",
            rel: "",
            src: "",
            alt: "",
            width: 0,
            height: 0,
            type: "",
            placeholder: "",
            children: [],
            parentNode: null,
            style: {},
            dataset: {},
            _attrs: attrs,
            classList: {
                _set: new Set(),
                add(cls) { this._set.add(cls); },
                remove(cls) { this._set.delete(cls); },
                toggle(cls) { if (this._set.has(cls)) { this._set.delete(cls); return false; } this._set.add(cls); return true; },
                contains(cls) { return this._set.has(cls); }
            },
            setAttribute(name, value) {
                attrs[String(name)] = String(value);
                if (name === "id") el.id = String(value);
                else if (name === "class") el.className = String(value);
                else if (name === "width") el.width = parseInt(value, 10) || 0;
                else if (name === "height") el.height = parseInt(value, 10) || 0;
            },
            getAttribute(name) {
                if (name === "id") return el.id;
                if (name === "class") return el.className;
                if (name === "width") return el.width;
                if (name === "height") return el.height;
                return Object.prototype.hasOwnProperty.call(attrs, name) ? attrs[name] : null;
            },
            hasAttribute(name) { return el.getAttribute(name) !== null; },
            removeAttribute(name) { delete attrs[name]; },
            querySelector(sel) {
                const want = String(sel).toUpperCase();
                const stack = el.children.slice();
                while (stack.length > 0) {
                    const n = stack.shift();
                    if (n.tagName === want) return n;
                    if (n.children) stack.push.apply(stack, n.children);
                }
                return null;
            },
            querySelectorAll(sel) {
                const want = String(sel).toUpperCase();
                const found = [];
                const stack = el.children.slice();
                while (stack.length > 0) {
                    const n = stack.shift();
                    if (n.tagName === want) found.push(n);
                    if (n.children) stack.push.apply(stack, n.children);
                }
                return found;
            },
            appendChild(child) {
                if (child && child.parentNode) child.parentNode.removeChild(child);
                child.parentNode = el;
                el.children.push(child);
                return child;
            },
            insertBefore(child, ref) {
                if (child && child.parentNode) child.parentNode.removeChild(child);
                child.parentNode = el;
                const i = el.children.indexOf(ref);
                if (i < 0) el.children.push(child);
                else el.children.splice(i, 0, child);
                return child;
            },
            removeChild(child) {
                const i = el.children.indexOf(child);
                if (i >= 0) { el.children.splice(i, 1); child.parentNode = null; }
                return child;
            },
            remove() { if (el.parentNode) el.parentNode.removeChild(el); },
            focus() {},
            blur() {},
            click() {
                const hs = (el._handlers && el._handlers.click) || [];
                for (const fn of hs) fn({ target: el, preventDefault() {}, stopPropagation() {} });
            },
            getContext(type) {
                if (type !== "2d") return null;
                return {
                    fillStyle: "#000", strokeStyle: "#000", lineWidth: 1,
                    globalAlpha: 1, font: "10px sans-serif",
                    textAlign: "left", textBaseline: "alphabetic",
                    beginPath() {}, closePath() {}, moveTo() {}, lineTo() {},
                    arc() {}, fill() {}, stroke() {}, clearRect() {},
                    fillRect() {}, strokeRect() {}, rect() {},
                    save() {}, restore() {}, translate() {}, rotate() {}, scale() {},
                    transform() {}, setTransform() {},
                    fillText() {}, strokeText() {},
                    measureText(text) { return { width: String(text).length * 6 }; },
                    drawImage() {},
                    createLinearGradient() { return { addColorStop() {} }; }
                };
            },
            addEventListener(type, fn) { el._handlers = el._handlers || {}; (el._handlers[type] = el._handlers[type] || []).push(fn); },
            removeEventListener(type, fn) {
                const hs = el._handlers && el._handlers[type];
                if (!hs) return;
                const i = hs.indexOf(fn);
                if (i >= 0) hs.splice(i, 1);
            }
        };
        Object.defineProperty(el, "options", {
            get() { return el.children.filter(function (c) { return c.tagName === "OPTION"; }); },
            configurable: true
        });
        Object.defineProperty(el, "firstChild", {
            get() { return el.children.length > 0 ? el.children[0] : null; },
            configurable: true
        });
        Object.defineProperty(el, "innerHTML", {
            get() { return ""; },
            set(v) { if (v === "") { el.children.length = 0; } },
            configurable: true
        });
        return el;
    }
    const kofRoot = kofMakeEl("div");
    kofRoot.id = "kof-root";
    const kofElements = { "kof-root": kofRoot };
    const kofHead = kofMakeEl("head");
    const kofHtml = kofMakeEl("html");
    kofHtml.appendChild(kofHead);
    globalThis.document = {
        title: "",
        head: kofHead,
        body: kofRoot,
        documentElement: kofHtml,
        createElement(tag) { return kofMakeEl(tag); },
        createElementNS(ns, tag) { return kofMakeEl(tag); },
        createTextNode(text) { const t = kofMakeEl("#text"); t.textContent = String(text); return t; },
        getElementById(id) { return kofElements[id] || null; },
        querySelector(sel) { return kofRoot.querySelector(sel); },
        querySelectorAll(sel) { return kofRoot.querySelectorAll(sel); }
    };
    globalThis.window = globalThis;
    globalThis.__kofRegisterElement = function (id, el) { kofElements[id] = el; };
}

function kofEscapeHtml(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
            .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function kofSerialize(node) {
    if (!node) return "";
    const tag = (node.tagName ? node.tagName.toLowerCase() : "div");
    let attrs = "";
    if (node.id) attrs += ' id="' + kofEscapeHtml(node.id) + '"';
    if (node.className) attrs += ' class="' + kofEscapeHtml(node.className) + '"';
    if (node.src) attrs += ' src="' + kofEscapeHtml(node.src) + '"';
    const kids = Array.from(node.children || []);
    const inner = kids.map(kofSerialize).join("");
    if (tag === "hr" || tag === "iframe" || tag === "br" || tag === "img") {
        return "<" + tag + attrs + ">";
    }
    const content = inner.length > 0 ? inner : kofEscapeHtml(node.textContent || "");
    return "<" + tag + attrs + ">" + content + "</" + tag + ">";
}

export function kofUiSerializeHtml() {
    const root = document.getElementById("kof-root");
    if (!root) return "";
    const html = "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
            + "<title>" + kofEscapeHtml(document.title || "Kof") + "</title>\n"
            + "</head>\n<body>\n" + kofSerialize(root) + "\n</body>\n</html>\n";
    globalThis.kof__uiRootHtml = html;
    return html;
}

export function kofPrintln(x) {
    console.log(x);
}

// D-NULL-INTENT (#278): Boolean.valueOf(Z) no JS — normaliza
// truthy/falsy num true/false estrito, mas PRESERVA null (Bool?
// genuino de Map.get/put/remove agora carrega ausência real; o
// ternário cru `x ? true : false` colapsava null -> false,
// apagando a ausência no println/String.valueOf).
export function kofUiWindowNew(title) {
    if (typeof document === "undefined") {
        return -1;
    }
    kofUiInjectTheme();
    const root = document.getElementById("kof-root");
    if (!root) {
        return -1;
    }
    if (typeof window.__kofWindows === "undefined") {
        window.__kofWindows = {};
    }
    const id = Object.keys(window.__kofWindows).length + 1;
    const winEl = document.createElement("div");
    winEl.className = "kof-window";
    window.__kofWindows[id] = winEl;
    document.title = title;
    root.appendChild(winEl);
    return id;
}

// Kof UI theme — the same Dracula/VSCode aesthetic in every host
// (browser, webview, KofWebHost): one Kof program, one look.
function kofUiInjectTheme() {
    if (typeof document === "undefined") return;
    if (document.getElementById("kof-theme")) return;
    const style = document.createElement("style");
    style.id = "kof-theme";
    style.textContent = [
        ":root { --bg:#282a36; --fg:#f8f8f2; --panel:#21222c; --border:#2e303e;",
        "  --hover:#2e303e; --accent:#8be9fd; --dim:#6272a4; --output:#50fa7b; }",
        "html, body { margin:0; height:100%; overflow:hidden; }",
        "body { background:var(--bg); color:var(--fg); font-family:",
        '  "Cascadia Code", "Fira Code", Consolas, Menlo, monospace; }',
        ".kof-label { color:var(--output); font-size:13px; line-height:1.5;",
        "  white-space:pre-wrap; padding:2px 0; }",
        // issues #75/#76 (10/09): o runtime AO VIVO não tinha NENHUMA
        // regra p/ Column/Row (renderizavam divs crus, sem flex) nem
        // p/ Button/Input/Textarea/Select (controles nativos crus).
        // Espelha o exportador ESTÁTICO (JsArtifactWriter) no MESMO
        // vocabulário de var(--…) do tema — paridade vivo↔estático.
        ".kof-column { display:flex; flex-direction:column; gap:8px; }",
        ".kof-row { display:flex; flex-direction:row; flex-wrap:wrap;",
        "  gap:8px; align-items:flex-start; }",
        ".kof-button { font-size:13px; padding:6px 14px; cursor:pointer;",
        "  background:var(--panel); color:var(--fg);",
        "  border:1px solid var(--border); border-radius:6px; }",
        ".kof-button:hover { background:var(--hover); }",
        ".kof-input, .kof-textarea, .kof-select { font-size:13px; padding:6px 10px;",
        "  background:var(--panel); color:var(--fg); font-family:inherit;",
        "  border:1px solid var(--border); border-radius:6px; }",
        ".kof-input { width:100%; }",
        ".kof-view { box-sizing:border-box; }",
        ".kof-window { box-sizing:border-box; padding:16px; border-radius:8px;",
        "  border:1px solid var(--border); background:var(--bg);",
        "  display:flex; flex-direction:column; gap:8px; }"
    ].join("\n");
    (document.head || document.documentElement).appendChild(style);
}

export function kofUiWindowSetTitle(window, title) {
    if (typeof document !== "undefined") {
        document.title = title;
    }
}

export function kofUiWindowBind(win, label) {
    if (typeof document === "undefined") {
        return;
    }
    const winEl = globalThis.window && globalThis.window.__kofWindows
            && globalThis.window.__kofWindows[win];
    if (!winEl) return;
    // Component Core: a component binds under the window and mounts
    // (view + onMount) — lifecycle is automatic.
    const comp = kofUiComponents.get(label);
    if (comp) {
        if (comp.el) winEl.appendChild(comp.el);
        kofUiComponentMount(label);
        return;
    }
    const nodes = globalThis.window && globalThis.window.__kofNodes;
    const node = nodes && nodes[label];
    if (node) {
        winEl.appendChild(node);
    }
}

export function kofUiWindowShow(window) {
    kofUiSerializeHtml();
}
// ── Component Core (docs/ui/architecture.md) ─────────────
// A UI is a tree of components. A Component node carries: identity,
// state (Int), a view builder, lifecycle hooks, effects (auto-cleaned)
// and events. Rendering is KofJS; the framework (not the widget)
// owns the tree, the render schedule and the lifecycle.
const kofUiComponents = new Map();
let kofNodeSeq = 0;
const KOF_UI_EV = {
    click: "click", dblclick: "dblclick", mousedown: "mousedown",
    mouseup: "mouseup", mousemove: "mousemove", mouseenter: "mouseenter",
    mouseleave: "mouseleave", wheel: "wheel", keydown: "keydown",
    keyup: "keyup", focus: "focus", blur: "blur", input: "input", change: "change"
};

function kofUiRunFn(fn) {
    // a Kof lambda compiles to a class with an invoke() method;
    // plain functions pass through.
    return fn && typeof fn.invoke === "function" ? fn.invoke.bind(fn) : fn;
}

function kofUiReportError(where, e) {
    // §266-filha: os catches deste módulo ENGOLIAM o throw do
    // código do usuário — view que crashava = UI vazia SEM NENHUMA
    // mensagem no console do browser (a lição do §266: o loop estava
    // errado, mas QUALQUER outro crash de view continuava silencioso
    // p/ UI e barulhento só headless). Mantém a resiliência (um
    // component quebrado não derruba os irmãos do flush) mas TORNA
    // O ERRO VISÍVEL: console.error com contexto + o throw original
    // (stack quando houver), espelhando o stderr do JVM/Script.
    const detail = e && (e.stack || e.message) ? (e.stack || e.message) : String(e);
    try {
        (console.error || console.log)("[kof] " + where + ": " + detail);
    } catch (ignored) {}
}

function kofUiRender(c) {
    // rebuild the component's child subtree: run the view builder
    // with the current state, then swap the fresh DOM in place.
    // (handle diffing is a Phase-9 optimization)
    let rootId = 0;
    try {
        const v = kofUiRunFn(c.view);
        rootId = v ? v(c.state) : 0;
    } catch (e) {
        kofUiReportError("view render threw for component " + (c && c.name), e);
        rootId = 0;
    }
    if (c.el) {
        const oldEl = window.__kofNodes && window.__kofNodes[c.root];
        if (c.root !== rootId && oldEl
                && oldEl.parentNode === c.el && oldEl.parentNode.removeChild) {
            c.el.removeChild(oldEl);
        }
        const rootEl = window.__kofNodes && window.__kofNodes[rootId];
        if (rootEl && rootEl.parentNode !== c.el) {
            c.el.appendChild(rootEl);
        }
    }
    c.root = rootId;
}

function kofUiRunEffect(n, f) {
    let result;
    try {
        result = f();
    } catch (e) {
        kofUiReportError("effect threw", e);
        result = null;
    }
    n.effects.push(result);
}

export function kofUiComponentMount(c) {
    const n = kofUiComponents.get(c);
    if (!n || n.mounted) return;
    n.mounted = true;
    // mount: (mount view) -> onMount() -> effects — deterministic
    if (n.view) kofUiRender(n);
    const om = kofUiRunFn(n.onMountFn);
    if (om) {
        try { om(); } catch (e) { kofUiReportError("onMount threw", e); }
    }
    for (const f of n.effectFns) kofUiRunEffect(n, f);
}

export function kofUiWidgetOn(id, type, handler) {
    if (!type || !handler) return;
    const node = window.__kofNodes && window.__kofNodes[id];
    if (!node) return;
    node._kofHandlers = node._kofHandlers || {};
    const domType = KOF_UI_EV[type] || type;
    const arr = node._kofHandlers[domType];
    if (arr) arr.push(handler);
    else node._kofHandlers[domType] = [handler];
    if (typeof node.addEventListener === "function") {
        node.addEventListener(domType, function (ev) {
            kofUiDispatchWidgetEvent(id, domType, ev);
        });
    }
}

export function kofUiLinkNew(text, url) {
    if (typeof document === "undefined") return -1;
    const a = document.createElement("a");
    a.textContent = text;
    a.href = url;
    a.target = "_blank";
    a.rel = "noopener";
    a.className = "kof-link";
    if (typeof window.__kofNodes === "undefined") window.__kofNodes = {};
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = a;
    return id;
}
// ── Font ───────────────────────────────────────────
export function kofUiLabelNew(text) {
    if (typeof document === "undefined") {
        return -1;
    }
    const span = document.createElement("span");
    span.textContent = text;
    span.className = "kof-label";
    if (typeof window.__kofNodes === "undefined") {
        window.__kofNodes = {};
    }
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = span;
    return id;
}

function kofUiCreateNode(tag, className) {
    if (typeof document === "undefined") {
        return -1;
    }
    const el = document.createElement(tag);
    el.className = className;
    if (typeof window.__kofNodes === "undefined") {
        window.__kofNodes = {};
    }
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = el;
    return id;
}

function kofUiSetAction(id, action) {
    if (!action || typeof document === "undefined") {
        return;
    }
    window.__kofActions = window.__kofActions || {};
    window.__kofActions[id] = action;
    const node = window.__kofNodes[id];
    if (node && typeof node.addEventListener === "function") {
        node.addEventListener("click", function () {
            action.invoke();
        });
    }
}

export function kofUiButtonNewAction(text, action) {
    const id = kofUiCreateNode("button", "kof-button");
    if (id < 0) {
        return -1;
    }
    window.__kofNodes[id].textContent = text;
    kofUiSetAction(id, action);
    return id;
}

export function kofUiColumnNew(ids) {
    const id = kofUiCreateNode("div", "kof-column");
    if (id < 0) {
        return -1;
    }
    const node = window.__kofNodes[id];
    if (ids) {
        for (const childId of ids) {
            const child = window.__kofNodes[childId];
            if (child) {
                node.appendChild(child);
            }
        }
    }
    return id;
}

export function kofUiRowNew(ids) {
    const id = kofUiCreateNode("div", "kof-row");
    if (id < 0) {
        return -1;
    }
    const node = window.__kofNodes[id];
    if (ids) {
        for (const childId of ids) {
            const child = window.__kofNodes[childId];
            if (child) {
                node.appendChild(child);
            }
        }
    }
    return id;
}

export function kofUiCanvasNew(w, h) {
    if (typeof document === "undefined") return -1;
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    canvas.className = "kof-canvas";
    canvas.style.display = "block";
    const ctx = canvas.getContext("2d");
    if (typeof window.__kofNodes === "undefined") window.__kofNodes = {};
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = canvas;
    window.__kofCanvasCtx = window.__kofCanvasCtx || {};
    window.__kofCanvasCtx[id] = ctx;
    // renderiza standalone: anexa ao root (w.bind(c) re-parenteia
    // para a janela — appendChild remove do pai anterior)
    const root = document.getElementById("kof-root");
    if (root) root.appendChild(canvas);
    return id;
}
export function kofUiCanvasBeginPath(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.beginPath();
}
export function kofUiCanvasClosePath(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.closePath();
}
export function kofUiCanvasMoveTo(id, x, y) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.moveTo(x, y);
}
export function kofUiCanvasLineTo(id, x, y) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.lineTo(x, y);
}
export function kofUiCanvasFill(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.fill();
    kofUiSerializeHtml();
}
export function kofUiCanvasSetFill(id, color) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.fillStyle = kofUiColorToCss(color);
}
export function kofUiAudioNew(src) {
    const id = kofUiCreateNode("audio", "kof-audio");
    if (id < 0) {
        return -1;
    }
    window.__kofNodes[id].src = src;
    return id;
}

export function kofUiAudioSetSrc(audio, src) {
    if (typeof document !== "undefined" && window.__kofNodes && window.__kofNodes[audio]) {
        window.__kofNodes[audio].src = src;
    }
}

export function kofUiAudioPlay(audio) {
    if (typeof document !== "undefined" && window.__kofNodes && window.__kofNodes[audio]
            && typeof window.__kofNodes[audio].play === "function") {
        window.__kofNodes[audio].play();
    }
}
// ── Layout primitives (docs/ui/architecture.md §2.8) ──────
// CSS-first: the framework never computes pixel positions; each
// primitive maps to a flex/grid CSS pattern.
export function kofUiColorToCss(color) {
    const r = (color >>> 24) & 0xFF;
    const g = (color >>> 16) & 0xFF;
    const b = (color >>> 8) & 0xFF;
    const a = color & 0xFF;
    if (a === 255) {
        return "rgb(" + r + ", " + g + ", " + b + ")";
    }
    return "rgba(" + r + ", " + g + ", " + b + ", " + a + ")";
}

export function kofListNew() {
    return [];
}

export function kofListAdd(list, value) {
    list.push(value);
}

export function kofListGet(list, index) {
    if (index < 0 || index >= list.length) {
        throw new Error("Index out of bounds: " + index + " (size " + list.length + ")");
    }
    return list[index];
}
// §103.1 (#103): decode<Map<String,T>> no JS — monta um Map
// real (o else dava objeto puro: m.size/m.get quebravam); com
// decoder, cada valor é bindado à classe.
// ── Web runtime (WEB001) — GraalJS HttpServer com handler invoke
// Handler lambda tem metodo invoke(); usamos Value para interop.
const kofTimeJobs = new Map();
const kofTimeSeq = { value: 0 };
function kofTimeRunJob(fn) {
    if (typeof fn.invoke === 'function') fn.invoke();
    else if (typeof fn === 'function') fn();
}
export function kofTimeInterval(ms, fn) {
    if (typeof setInterval === 'function') {
        return "n" + String(setInterval(() => kofTimeRunJob(fn), ms));
    }
    const id = "c" + (++kofTimeSeq.value);
    kofTimeJobs.set(id, { ms: ms, run: () => kofTimeRunJob(fn), next: Date.now() + ms });
    return id;
}
// ── kof.security (docs/stdlib/security.md §5) ────────────────────
// ── AES-256-GCM (SECN002 fechado 01/09) ───────────────────
// Puro JS (roda no GraalJS e no browser). Formato idêntico ao
// JVM/Native: aesgcm$<ivB64>$<ct||tagB64>, key 32 bytes (64 hex),
// IV 12 bytes aleatórios, tag 128-bit. S-box FIPS 197; GHASH/CTR
// NIST SP 800-38D. Validado byte-a-byte contra node:crypto e o
// vetor NIST (KofSecurityTest.aesGcmJsRoundTrip + paridade JVM).

    // ── kof.validation (STDLIB S12) — pontuação BR ─────────────
    // 11 dígitos => DDD.DDD.DDD-DD; 8 => DDDDD-DDDD; senão original
    // (null => null; nunca lança — face leniente da lane).
        // ── kof.math (STDLIB S1) — Int-only, paridade JVM/Native ─────

// kof.random (STDLIB S10a) — face não-críptográfica. Entropia do
// SO: kof_platform (SecureRandom no runner Node); no browser o
// proxy lança, cai em crypto.getRandomValues. bound<=0 -> 0
// (leniente — contrato do plano; security.randomInt lança).
// ── kof.math S1b.1 — Double puros (paridade JVM/Native) ─────
// Bool = 1/0 (chokepoint §93 cuida do ==true).
// ── §181 (13/09): casts Double/Float -> Int/Long SATURANTES
// (JLS 5.1.3 — NaN => 0, > MAX => MAX, < MIN => MIN). O
// Math.trunc cru dava 3e9 (fora do Int32), NaN e Infinity.
// Long = BigInt saturado (paridade 64-bit do §81).
// ── §264: Double/Float → string no formato do JDK ─────────────
// Regra Double.toString: significante com round-trip mínimo,
// decimal quando -3 <= exp < 7, senão E±m sem leading-zero.
// Sempre ao menos um dígito fracionário (4 → "4.0").

// ── kof.net (STDLIB S8) ────────────────────────────────────────

// ── kof.uuid (STDLIB S3b / S3b.2) ──────────────────────────────
// v4: kof_platform.randomBytesHex (16 B) -> RFC 4122

        // ── kof.strings (STDLIB S3.2) — whitespace ──────────────────
// Fase 5 (docs/ui/architecture.md §2.5): target -> bubbles up the
// component tree (child -> parent). The handler receives a Kof
// Event with type + stopPropagation support.
function kofUiMakeEvent(domType, ev) {
    const raw = ev || null;
    return {
        stopped: false,
        // Kof accesses event kind as e.type() (a method call)
        type() { return domType; },
        stopPropagation() { this.stopped = true; },
        // UI006: key/value/x/y do DOM event real (null/vazio no
        // host mock e no emit sintético).
        key() {
            return raw && typeof raw.key === "string" ? raw.key : "";
        },
        value() {
            if (!raw) return "";
            const t = raw.target;
            return t && typeof t.value === "string" ? t.value : "";
        },
        x() { return raw && typeof raw.clientX === "number" ? raw.clientX : 0; },
        y() { return raw && typeof raw.clientY === "number" ? raw.clientY : 0; },
        // UI006 residual: alvo do evento como id do nó (fallback
        // tagName minúscula quando sem setId; "" fora do browser).
        target() {
            const t = raw && raw.target;
            if (!t) return "";
            return t.id ? String(t.id)
                    : (t.tagName ? t.tagName.toLowerCase() : "");
        },
        relatedTarget() {
            const t = raw && raw.relatedTarget;
            if (!t) return "";
            return t.id ? String(t.id)
                    : (t.tagName ? t.tagName.toLowerCase() : "");
        },
        // raw DOM event passthrough (null in the host mock)
        raw: raw
    };
}

// UI006: dispatch de widget DOM (fora da árvore de Component) —
// o handler recebe o kofEv construído do evento DOM real.
function kofUiDispatchWidgetEvent(id, domType, ev) {
    const node = window.__kofNodes && window.__kofNodes[id];
    if (!node) return;
    const h = node._kofHandlers && node._kofHandlers[domType];
    if (!h) return;
    const kofEv = kofUiMakeEvent(domType, ev);
    for (const fn of h) {
        try {
            if (typeof fn.invoke === "function") fn.invoke(kofEv);
            else fn(kofEv);
        } catch (e) {}
    }
}
